#!/bin/bash

alias zr="[ -f ~/.zshrc ] && source ~/.zshrc || source ~/.bashrc"
alias zv="[ -f ~/.zshrc ] && vim ~/.zshrc || vim ~/.bashrc"
alias st="git status"
alias nr="yarn run"
alias gc="git commit -a"
alias gcm="git commit -am"
alias gl="git log"
alias gsl="git shortlog"
