#!/bin/bash

sudo apt-get update
sudo apt-get install build-essential libssl-dev curl git -y
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
source $HOME/.nvm/nvm.sh
nvm install stable
