#!/bin/bash

sudo apt-get update
sudo apt-get install zsh git-core -y
wget https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh -O - | zsh
chsh -s `which zsh`
echo "zsh set as default shell. You must restart your computer for zsh to work."
