#!/bin/bash

# about: Prints the local ip address. Pass "external" to get the external ip address.

if [[ $1 == "external" ]]; then
  dig +short myip.opendns.com @resolver1.opendns.com
else
  ifconfig | grep -m 1 -oP "(?<=inet addr:)(\d\d?\d?.\d\d?\d?.\d\d?\d?.\d\d?\d?)"
fi
